DROP TABLE IF EXISTS ride;
DROP TABLE IF EXISTS house;
DROP TABLE IF EXISTS rating;
DROP TABLE IF EXISTS passenger;
DROP TABLE IF EXISTS driver;
DROP TABLE IF EXISTS streets;


CREATE TABLE streets (
id INTEGER PRIMARY KEY AUTO_INCREMENT NOT NULL,
name VARCHAR(30) UNIQUE NOT NULL);


CREATE TABLE house  (
id INTEGER PRIMARY KEY AUTO_INCREMENT NOT NULL,
street INTEGER NOT NULL,
house_number  VARCHAR(30) NOT NULL,
FOREIGN KEY(street) REFERENCES streets(id),
UNIQUE (street, house_number));


CREATE TABLE passenger (
id INTEGER PRIMARY KEY AUTO_INCREMENT NOT NULL,
name VARCHAR(30));


CREATE TABLE driver (
id INTEGER PRIMARY KEY AUTO_INCREMENT NOT NULL,
name VARCHAR(30));


CREATE TABLE rating (
id INTEGER PRIMARY KEY AUTO_INCREMENT NOT NULL,
passenger_id INTEGER NOT NULL,
INDEX idx_rating_passenger_id (passenger_id),
score INTEGER NOT NULL,
FOREIGN KEY (passenger_id) REFERENCES passenger(id));


CREATE TABLE ride  (
id INTEGER PRIMARY KEY AUTO_INCREMENT NOT NULL,
passenger INTEGER NOT NULL,
driver INTEGER NOT NULL,     
Destination_address INTEGER,
Shipping_addresses INTEGER,
FOREIGN KEY(passenger) REFERENCES passenger (id),
FOREIGN KEY(driver) REFERENCES driver (id),    
FOREIGN KEY(Destination_address) REFERENCES house (id),
FOREIGN KEY(Shipping_addresses) REFERENCES house (id));