CREATE TABLE streets (
id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
name VARCHAR UNIQUE);

CREATE TABLE house  (
id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
street VARCHAR NOT NULL,
house_number  VARCHAR UNIQUE,
FOREIGN KEY(street) REFERENCES streets(id));

CREATE TABLE passenger  (
id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
name VARCHAR);

CREATE TABLE ride  (
id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
passenger VARCHAR NOT NULL,
Destination_address INTEGER,
Shipping_addresses INTEGER,
FOREIGN KEY(passenger) REFERENCES passenger (id),
FOREIGN KEY(Destination_address) REFERENCES house (id),
FOREIGN KEY(Shipping_addresses) REFERENCES house (id));
