- hosts: all
  become: true
  tasks:
    # Оновлення та оновлення системи
    - name: Update and upgrade apt packages
      apt:
        update_cache: yes
        upgrade: yes
        cache_valid_time: 3600

    # Встановлення Apache, MySQL, PHP та необхідних розширень
    - name: Install Apache, MySQL, PHP and required extensions
      apt:
        name:
          - apache2
          - mysql-server
          - php
          - php-mysql
          - libapache2-mod-php
          - php-curl
          - php-xml
          - php-zip
        state: present
        update_cache: yes

    # Увімкнення Apache та MySQL
    - name: Enable Apache and MySQL services
      service:
        name: "{{ item }}"
        state: started
        enabled: yes
      loop:
        - apache2
        - mysql

    # Встановлення pip3, якщо він відсутній
    - name: Install pip3
      apt:
        name: python3-pip
        state: present

    # Встановлення Python модуля для MySQL
    - name: Install required Python MySQL module
      pip:
        name: pymysql
        state: present

    # Створення MySQL credentials файлу для root
    - name: Create MySQL credentials file for root
      copy:
        dest: /root/.my.cnf
        content: |
            [client]
            user = root
            password = strongpassword
        mode: '0600'

    # Встановлення прав доступу до MySQL credentials файлу
    - name: Set ownership and permissions for MySQL credentials file
      file:
        path: /root/.my.cnf
        owner: root
        group: root
        mode: '0600'

    # Інші завдання...