- hosts: all
  become: true
  tasks:
    - name: Update and upgrade apt packages
      apt:
        update_cache: yes
        upgrade: dist

    - name: Install Apache, MySQL, PHP and required extensions
      apt:
        name:
          - apache2
          - mysql-server
          - php
          - php-mysql
          - php-curl
          - php-gd
          - php-mbstring
          - php-xml
          - php-xmlrpc
          - unzip
        state: present

    - name: Enable Apache and MySQL services
      service:
        name: "{{ item }}"
        state: started
        enabled: true
      loop:
        - apache2
        - mysql

    - name: Secure MySQL Installation
      shell: |
        sudo mysql -u root -p
        sudo mysql -e "ALTER USER 'root'@'localhost' IDENTIFIED WITH 'mysql_native_password' BY '{{ mysql_root_password }}';"
        sudo mysql -e "DELETE FROM mysql.user WHERE User='';"
        sudo mysql -e "DELETE FROM mysql.db WHERE Db='test' OR Db='test_%';"
        sudo mysql -e "FLUSH PRIVILEGES;"
      vars:
        mysql_root_password: "strongpassword"

    - name: Create a MySQL Database and User for WordPress
      mysql_db:
        name: wordpress
        state: present

    - name: Create a MySQL User for WordPress
      mysql_user:
        name: wp_user
        password: wp_password
        priv: 'wordpress.*:ALL'
        host: "%"
        state: present