- name: Configure WordPress server
  hosts: all
  become: true
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Ensure Apache and PHP are installed
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      loop:
        - apache2
        - php
        - php-mysql
        
    - name: Start and enable Apache
      systemd:
        name: apache2
        state: started
        enabled: yes
