- hosts: all
  become: true
  vars:
    mysql_root_password: "strongpassword"

  tasks:
    # Оновлення та оновлення системи
    - name: Update and upgrade apt packages
      apt:
        update_cache: yes
        upgrade: yes
        cache_valid_time: 3600

    # Встановлення Apache, MySQL, PHP та необхідних розширень
    - name: Install Apache, MySQL, PHP and required extensions
      apt:
        name:
          - apache2
          - mysql-server
          - php
          - php-mysql
          - libapache2-mod-php
          - php-curl
          - php-xml
          - php-zip
        state: present
        update_cache: yes

    # Увімкнення Apache та MySQL
    - name: Enable Apache and MySQL services
      service:
        name: "{{ item }}"
        state: started
        enabled: yes
      loop:
        - apache2
        - mysql

    # Встановлення pip3, якщо він відсутній
    - name: Install pip3
      apt:
        name: python3-pip
        state: present

    # Встановлення Python модуля для MySQL
    - name: Install required Python MySQL module
      pip:
        name: pymysql
        state: present

    # Створення файлу з обліковими даними MySQL для root
    - name: Create MySQL credentials file for root
      copy:
        dest: /root/.my.cnf
        content: |
          [client]
          user = root
          password = "{{ mysql_root_password }}"
        mode: '0600'

    # Захист MySQL: видалення тестових даних і анонімних користувачів
    - name: Secure MySQL Installation
      shell: |
        mysql -u root -e "UPDATE mysql.user SET authentication_string=PASSWORD('{{ mysql_root_password }}') WHERE User='root';"
        mysql -u root -e "DELETE FROM mysql.user WHERE User='';"
        mysql -u root -e "DELETE FROM mysql.db WHERE Db='test' OR Db='test_%';"
        mysql -u root -e "FLUSH PRIVILEGES;"

    # Зміна автентифікації root на mysql_native_password
    - name: Change root authentication to mysql_native_password
      shell: |
        mysql -u root --skip-grant-tables -e "ALTER USER 'root'@'localhost' IDENTIFIED WITH 'mysql_native_password' BY '{{ mysql_root_password }}';"
        mysql -u root -e "FLUSH PRIVILEGES;"

    # Створення бази даних для WordPress
    - name: Create a MySQL Database for WordPress
      mysql_db:
        name: wordpress
        state: present

    # Створення користувача для WordPress з доступом до бази даних
    - name: Create a MySQL User for WordPress
      mysql_user:
        name: wp_user
        password: wp_password
        priv: 'wordpress.*:ALL'
        host: "%"
        state: present