- name: Configure WordPress AMI
  hosts: all
  become: true

  vars:
    ansible_python_interpreter: /usr/bin/python3
    mysql_root_password: "your_strong_password"
    wordpress_db_user: "wp_user"
    wordpress_db_password: "strong_password"
    wordpress_db_name: "wordpress"

  tasks:
    - name: Update and upgrade system
      apt:
        update_cache: yes
        upgrade: dist

    - name: Set MySQL root password
      debconf:
        name: mysql-server
        question: mysql-server/root_password
        value: "{{ mysql_root_password }}"
        vtype: password

    - name: Confirm MySQL root password
      debconf:
        name: mysql-server
        question: mysql-server/root_password_again
        value: "{{ mysql_root_password }}"
        vtype: password

    - name: Install LAMP stack and dependencies
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - apache2
        - mysql-server
        - php
        - php-mysql
        - libapache2-mod-php
        - unzip
        - python3-pymysql

    - name: Update MySQL authentication method
      mysql_user:
        name: root
        host: localhost
        password: "{{ mysql_root_password }}"
        login_user: root
        login_password: "{{ mysql_root_password }}"
        auth_plugin: mysql_native_password

    - name: Configure MySQL database
      mysql_db:
        name: "{{ wordpress_db_name }}"
        state: present
      login_user: root
      login_password: "{{ mysql_root_password }}"

    - name: Configure MySQL user
      mysql_user:
        name: "{{ wordpress_db_user }}"
        password: "{{ wordpress_db_password }}"
        priv: "{{ wordpress_db_name }}.*:ALL"
        host: localhost
        state: present
      login_user: root
      login_password: "{{ mysql_root_password }}"

    - name: Download WordPress
      get_url:
        url: https://wordpress.org/latest.tar.gz
        dest: /tmp/latest.tar.gz

    - name: Extract WordPress
      unarchive:
        src: /tmp/latest.tar.gz
        dest: /var/www/html
        remote_src: yes

    - name: Set permissions for WordPress
      file:
        path: /var/www/html/wordpress
        state: directory
        owner: www-data
        group: www-data
        mode: '0755'
        recurse: yes

    - name: Enable Apache and MySQL
      systemd:
        name: "{{ item }}"
        enabled: yes
        state: started
      with_items:
        - apache2
        - mysql

    - name: Create Apache virtual host for WordPress
      copy:
        dest: /etc/apache2/sites-available/wordpress.conf
        content: |
          <VirtualHost *:80>
              ServerName wordpress.local
              DocumentRoot /var/www/html/wordpress
              <Directory /var/www/html/wordpress>
                  AllowOverride All
              </Directory>
          </VirtualHost>

    - name: Enable WordPress site
      command: a2ensite wordpress

    - name: Enable Apache rewrite module
      command: a2enmod rewrite

    - name: Restart Apache
      systemd:
        name: apache2
        state: restarted
