- hosts: all
  become: true
  tasks:
    - name: Update and upgrade apt packages
      apt:
        update_cache: yes
        upgrade: dist

    - name: Install Apache, MySQL, PHP and required extensions
      apt:
        name:
          - apache2
          - mysql-server
          - php
          - php-mysql
          - php-curl
          - php-gd
          - php-mbstring
          - php-xml
          - php-xmlrpc
          - unzip
        state: present

    - name: Enable Apache and MySQL services
      service:
        name: "{{ item }}"
        state: started
        enabled: true
      loop:
        - apache2
        - mysql

    - name: Secure MySQL Installation
      shell: |
       
       
    - name: Create a MySQL Database and User for WordPress
      mysql_db:
        name: wordpress
        state: present

    - name: Create a MySQL User for WordPress
      mysql_user:
        name: wp_user
        password: wp_password
        priv: 'wordpress.*:ALL'
        host: "%"
        state: present