- name: Configure WordPress server
  hosts: all
  become: true

  vars:
    ansible_python_interpreter: /usr/bin/python3

  tasks:
    - name: Update and upgrade system
      apt:
        update_cache: yes
        upgrade: dist

    - name: Set MySQL root password
      debconf:
        name: mysql-server
        question: mysql-server/root_password
        value: your_strong_password
        vtype: password

    - name: Confirm MySQL root password
      debconf:
        name: mysql-server
        question: mysql-server/root_password_again
        value: your_strong_password
        vtype: password

    - name: Install Python MySQL dependencies
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - python3-pymysql
        - python3-mysqldb   

    - name: Install LAMP stack
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - apache2
        - mysql-server
        - php
        - php-mysql
        - libapache2-mod-php
        - unzip

    - name: Update MySQL authentication method
      command: >
        mysql -u root --execute="ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'your_strong_password'; FLUSH PRIVILEGES;"

    - name: Configure MySQL
      mysql_user:
        name: wp_user
        password: strong_password
        priv: 'wordpress.*:ALL'
        host: localhost
        state: present
      login_user: root
      login_password: your_strong_password

    - name: Create WordPress database
      mysql_db:
        name: wordpress
        state: present
      login_user: root
      login_password: your_strong_password"

    - name: Download WordPress
      get_url:
        url: https://wordpress.org/latest.tar.gz
        dest: /tmp/latest.tar.gz

    - name: Extract WordPress
      unarchive:
        src: /tmp/latest.tar.gz
        dest: /var/www/html
        remote_src: yes

    - name: Set permissions for WordPress
      file:
        path: /var/www/html/wordpress
        state: directory
        owner: www-data
        group: www-data
        mode: '0755'
        recurse: yes

    - name: Enable Apache and MySQL
      systemd:
        name: "{{ item }}"
        enabled: yes
        state: started
      with_items:
        - apache2
        - mysql
