- hosts: all
  become: true
  tasks:
    # Оновлення та оновлення системи
    - name: Update and upgrade apt packages
      apt:
        update_cache: yes
        upgrade: yes
        cache_valid_time: 3600

    # Встановлення Apache, MySQL, PHP та необхідних розширень
    - name: Install Apache, MySQL, PHP and required extensions
      apt:
        name:
          - apache2
          - mysql-server
          - php
          - php-mysql
          - libapache2-mod-php
          - php-curl
          - php-xml
          - php-zip
          - php-mbstring
          - php-gd
          - php-soap
          - php-intl
          - php-bcmath
          - php-json
        state: present
        update_cache: yes

    # Увімкнення Apache та MySQL
    - name: Enable Apache and MySQL services
      service:
        name: "{{ item }}"
        state: started
        enabled: yes
      loop:
        - apache2
        - mysql

    # Встановлення pip3, якщо він відсутній
    - name: Install pip3
      apt:
        name: python3-pip
        state: present

    # Встановлення Python модуля для MySQL
    - name: Install required Python MySQL module
      pip:
        name: pymysql
        state: present

    # Створення MySQL credentials файлу для root
    - name: Create MySQL credentials file for root
      copy:
        dest: /root/.my.cnf
        content: |
            [client]
            user = root
            password = strongpassword
        mode: '0600'

    # Встановлення прав доступу до MySQL credentials файлу
    - name: Set ownership and permissions for MySQL credentials file
      file:
        path: /root/.my.cnf
        owner: root
        group: root
        mode: '0600'

    # Перевірка та зміна пароля для root в MySQL
    - name: Secure MySQL Installation
      shell: |
        sudo mysql -e "ALTER USER 'root'@'localhost' IDENTIFIED BY '{{ mysql_root_password }}';"
        sudo mysql -e "DELETE FROM mysql.user WHERE User='';"
        sudo mysql -e "DELETE FROM mysql.db WHERE Db='test' OR Db='test_%';"
        sudo mysql -e "FLUSH PRIVILEGES;"
      vars:
        mysql_root_password: "strongpassword"

    # Зміна способу автентифікації root на mysql_native_password
    - name: Change root authentication to mysql_native_password
      shell: |
        sudo mysql -e "ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY '{{ mysql_root_password }}';"
        sudo mysql -e "FLUSH PRIVILEGES;"
      vars:
        mysql_root_password: "strongpassword"

    # Перезапуск MySQL сервісу
    - name: Restart MySQL service
      service:
        name: mysql
        state: restarted

    # Створення бази даних для WordPress
    - name: Create a MySQL Database for WordPress
      mysql_db:
        name: wordpress
        state: present
        login_user: root
        login_password: "{{ mysql_root_password }}"
      vars:
        mysql_root_password: "strongpassword"

    # Створення користувача для WordPress з доступом до бази даних
    - name: Create a MySQL User for WordPress
      mysql_user:
        name: wp_user
        password: wp_password
        priv: 'wordpress.*:ALL'
        host: "%"
        state: present
        login_user: root
        login_password: "{{ mysql_root_password }}"
      vars:
        mysql_root_password: "strongpassword"

    # Завантаження WordPress
    - name: Download WordPress
      get_url:
        url: https://wordpress.org/latest.tar.gz
        dest: /tmp/wordpress.tar.gz

    # Розпакування WordPress
    - name: Extract WordPress
      unarchive:
        src: /tmp/wordpress.tar.gz
        dest: /var/www/
        remote_src: yes

    # Очищення попередньої установки WordPress
    - name: Clear previous WordPress installation
      file:
        path: /var/www/html
        state: absent

    # Переміщення файлів WordPress у web-директорію
    - name: Move WordPress files
      command: mv /var/www/wordpress/* /var/www/html/

    # Встановлення правильних прав доступу
    - name: Set permissions for WordPress files
      file:
        path: /var/www/html/
        owner: www-data
        group: www-data
        mode: '0755'
        recurse: yes

    # Створення wp-config.php файлу
    - name: Create wp-config.php
      command: cp /var/www/html/wp-config-sample.php /var/www/html/wp-config.php

    - name: Update wp-config.php for database connection
      lineinfile:
        path: /var/www/html/wp-config.php
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
      with_items:
        - { regexp: "DB_NAME', '.*'", line: "define('DB_NAME', 'wordpress');" }
        - { regexp: "DB_USER', '.*'", line: "define('DB_USER', 'wp_user');" }
        - { regexp: "DB_PASSWORD', '.*'", line: "define('DB_PASSWORD', 'wp_password');" }
        - { regexp: "DB_HOST', '.*'", line: "define('DB_HOST', 'localhost');" }

    # Налаштування Apache для WordPress
    - name: Configure Apache for WordPress
      copy:
        dest: /etc/apache2/sites-available/wordpress.conf
        content: |
          <VirtualHost *:80>
            DocumentRoot /var/www/html
            <Directory /var/www/html>
              AllowOverride All
            </Directory>
          </VirtualHost>

    - name: Enable WordPress site and mod_rewrite
      command: a2ensite wordpress && a2enmod rewrite

    - name: Restart Apache
      service:
        name: apache2
        state: restarted
