name: Run Script on Push

on:
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Run Inline Bash Script
        run: |
          echo "Starting the script..."
          
          # Отримати ім'я поточної гілки
          BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)
          echo "Branch: $BRANCH_NAME"
          
          # Перевірка дати
          CURRENT_DATE=$(date)
          echo "Current date is: $CURRENT_DATE"
          
          echo "Script finished!"
