name: deploy ec2 instance

on:
  workflow_dispatch:

jobs:
  deploy-instance:
    name: deploy EC2
    runs-on: ubuntu-latest

    
    steps:
    # 1. Завантаження репозиторію
    - name: Checkout repository
      uses: actions/checkout@v3

    # 2. Налаштування AWS CLI (замість передачі ключів вручну)
    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-central-1

   
    # 5. Встановлення Terraform
    - name: Install Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.7

    # 6. Ініціалізація Terraform
    - name: Terraform Init
      run: terraform init

    # 7. Застосування Terraform
    - name: Terraform Apply
      id: apply
      run: |
        terraform apply -auto-approve -var "ami_id=ami-0629230e074c580f2"

    # 8. Виведення IP-адреси
    - name: Get Public IP
      run: |
        PUBLIC_IP=$(terraform output -raw public_ip)
        echo "Instance Public IP: $PUBLIC_IP"
        echo "PUBLIC_IP=$PUBLIC_IP" >> $GITHUB_ENV

    # 9. Видалення інстанса
#    - name: Terraform Destroy
#      if: always()
#      run: |
#        terraform destroy -auto-approve -var "ami_id=ami-0629230e074c580f2"








      
      

      